# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

# include pycss file
from pycss import PyCss

css = PyCss()



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        MainWindow.setStyleSheet(css.load("Css\\main.css"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(310, 10, 191, 51))
        self.title.setObjectName("title")
        self.copyrights = QtWidgets.QLabel(self.centralwidget)
        self.copyrights.setGeometry(QtCore.QRect(310, 480, 179, 14))
        self.copyrights.setObjectName("copyrights")
        self.playlistBtn = QtWidgets.QPushButton(self.centralwidget)
        self.playlistBtn.setGeometry(QtCore.QRect(330, 180, 131, 41))
        self.playlistBtn.setObjectName("playlistBtn")
        self.videoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.videoBtn.setGeometry(QtCore.QRect(330, 270, 131, 41))
        self.videoBtn.setObjectName("videoBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KDownloader | Main"))
        self.title.setText(_translate("MainWindow", "Youtube Downloader"))
        self.copyrights.setText(_translate("MainWindow", "Copyrights for Crystal & Kurayami"))
        self.playlistBtn.setText(_translate("MainWindow", "Playlist"))
        self.videoBtn.setText(_translate("MainWindow", "Video"))
        

