# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\playlist_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from pycss import PyCss

css = PyCss()


class Playlist_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        MainWindow.setStyleSheet(css.load("Css\\playlistDownloader.css"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 190, 321, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(320, 30, 181, 41))
        self.header.setObjectName("header")
        self.mp3_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mp3_btn.setGeometry(QtCore.QRect(290, 270, 75, 31))
        self.mp3_btn.setObjectName("mp3_btn")
        self.mp4_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mp4_btn.setGeometry(QtCore.QRect(430, 270, 75, 31))
        self.mp4_btn.setObjectName("mp4_btn")
        self.backArrowBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backArrowBtn.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.backArrowBtn.setObjectName("backArrowBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KDownloader | Playlist Downloader"))
        self.header.setText(_translate("MainWindow", "Playlist Downloader"))
        self.mp3_btn.setText(_translate("MainWindow", "MP3"))
        self.mp4_btn.setText(_translate("MainWindow", "MP4"))
        self.backArrowBtn.setText(_translate("MainWindow", "Back"))

